# Generated by Django 6.0.2 on 2026-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('author', models.CharField(max_length=256, verbose_name='Автор')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(verbose_name='Осталось на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
