# Generated by Django 6.0.2 on 2026-02-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
